### PR TITLE
Support reduced frame size in validation

### PR DESCRIPTION
**Pull request by timholy**
This fixes a bug reported via email by @jona125. The key change is allowing the user to pass `vertical_lines` to `write_commands` to communicate the anticipated frame size. I am not sure whether there's any way of using the same value to control the acquisition.

I'm happy to accept feedback on any of this, including the naming of the parameter `vertical_lines`.

### CODE REVIEW

**Comment by kdw503** [comment]
Opps! I already did this and about to do pull request. But your commit looks better.

**Comment by timholy** [comment]
So sorry! I should have coordinated with you.

**Comment by timholy** [comment]
Anything that you like better about yours, feel free to add to this branch.

**Comment by kdw503** [comment]
Other than this topic, If user can use ImaginePlots.jl with ImagineInterface it would be better to work. But ImaginPlots uses UnitfulPlots.jl which is still live in julia0.7 so I forked it to my repo. and added Project.toml then it still works. Is it ok to fork the UnitfulPlots.jl to our Holylab repo. and do the pull request of the modifying in ImaginePlots.jl?

**Comment by timholy** [comment]
Sure. But have you submitted a PR to update the official UnitfulPlots.jl? I don't see any open pull requests.

**Comment by kdw503** [comment]
I didn't do yet.

**Comment by timholy** [comment]
Go for it! [The world is your oyster](https://idioms.thefreedictionary.com/the+world+is+your+oyster), don't be shy. You're good at this stuff!  :smiley:

**Pull request merged**
